### ISSUE TITLE
Wrong material.bin source file is chosen when building

### ISSUE THREAD

**Issue by devendrn** [veka0/lazurite#1]
When trying to build `Sky`, Lazurite picks `EndSky.material.bin` as source. 

Looking through the code, this seems to happen because Lazurite picks the first file that ends with `Sky.material.bin` from the material source list. I tried testing it by removing `EndSky.material.bin` from my material source folder and just keeping `Sky.material.bin` there. This time Lazurite picks the correct file, i.e `Sky.material.bin`.

Making this change in `lazurite/project/project.py`, line 65 will fix the issue:
```py
    for platform in platforms:
        for path in merge_source:
            if not name == os.path.split(path)[-1]: # fix
                continue
```
I didn't want to open a PR for single line edit

**Comment by veka0** [comment]
Thanks! Fixed in 0.1.4
